"""empty message

Revision ID: b846a0c5a5b9
Revises: b3c36a2e1461
Create Date: 2022-06-18 00:19:41.306469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b846a0c5a5b9'
down_revision = 'b3c36a2e1461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'character')
    op.drop_column('favorite', 'episode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('episode', sa.VARCHAR(length=250), nullable=True))
    op.add_column('favorite', sa.Column('character', sa.VARCHAR(length=250), nullable=True))
    op.create_foreign_key(None, 'favorite', 'character', ['character'], ['name'])
    op.create_foreign_key(None, 'favorite', 'episode', ['episode'], ['name'])
    # ### end Alembic commands ###
